base_url: http://localhost:3000
terrain_url: http://terrain
listen_port: 3000

logging:
    level: info
    label: sonora server

db:
    host: localhost
    port: 5432
    user: null
    password: null
    database: de

sessions:
    secret: "keyboard cat"
    secure_cookie: false
    ttl: 8

keycloak:
    server_url: "https://kc.cyverse.org/auth"
    realm: "CyVerse"
    client_id: null
    client_secret: null

intercom:
    app_id: aw5b6i5l
    enabled: true
    company_id: DE-DEV
    company_name: DISCOVERY ENVIRONMENT

admin:
    groups: core-services,tito-admins,tito-qa-admins,dev
    group_attribute_name: entitlement
