name: Chromatic CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.my_token }}
          projectToken: ${{ secrets.project_token }}
          exitZeroOnChanges: true
          allowConsoleErrors: true