name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Required to retrieve git history
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: check format
      run: |
        npx prettier --check ./src/**/*.js ./.storybook/**/*.js ./stories/**/*.js
    - name: eslint
      uses: stefanoeb/eslint-action@1.0.2
      with:
        files: src/ .storybook/ stories
    - uses: chromaui/action@v1
      with:
        projectToken: 2hhfm0frnwy
        exitZeroOnChanges: true
        allowConsoleErrors: true
